#bootstrap.yml
server:
  port: 8802

spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings: # 服务的整合处理
        input: # 这是一个通道的名字
          destination: MystudyExcange # 使用的Exchange定义
          content-type: application/json # 消息类型
          binder: defaultRabbit # 设置要绑定的消息服务的具体设置
#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

